### ISSUE TITLE
[New icon] Update/Add the new X(Twitter) Icon

### ISSUE THREAD

**Issue by mghenciu** [Ybbet/socicon#9]
Personally, I would keep for now both of them (twitter and X), and users can choose.
This is how Wodpress Editor does it, having both options available: 
![image](https://github.com/Ybbet/socicon/assets/52494172/23ca9f04-caa0-49dd-a1be-cfd29294fb64)

**Name of your icon :** X
**Color :** the default text color
**URL :** [Can you provide a URL to the site of your icon?](https://about.x.com/en/who-we-are/brand-toolkit)

You can also attach an svg file of your icon to this ticket to facilitate its integration into Socicon.
https://about.x.com/en/who-we-are/brand-toolkit

**Comment by Ybbet** [comment]
The icon was integrated in v3.7.2  https://github.com/Ybbet/socicon/releases/tag/v3.7.2

**Comment by mghenciu** [comment]
Thanks a lot for the quick update, @Ybbet 🚀
